In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#lire un fichier csv
df=pd.read_csv('data.csv')

#Afficher les 10 premier lignes
df.head(5)

X1   X2  X3  X4   X5    X6     X7  X8  y
0   6  148  72  35    0  33.6  0.627  50  1
1   1   85  66  29    0  26.6  0.351  31  0
2   8  183  64   0    0  23.3  0.672  32  1
3   1   89  66  23   94  28.1  0.167  21  0
4   0  137  40  35  168  43.1  2.288  33  1

In [3]:
#Afficher les informations du dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      768 non-null    int64  
 1   X2      768 non-null    int64  
 2   X3      768 non-null    int64  
 3   X4      768 non-null    int64  
 4   X5      768 non-null    int64  
 5   X6      768 non-null    float64
 6   X7      768 non-null    float64
 7   X8      768 non-null    int64  
 8   y       768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
df.describe()

X1          X2          X3          X4          X5          X6  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

               X7          X8           y  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [5]:
from sklearn.preprocessing import StandardScaler

# Sélection des colonnes à standardiser pour ne pas standariser les colonnes sauf Y
columns_to_standardize = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8']

# Création de l'objet StandardScaler et standardisation des colonnes sélectionnées
scaler = StandardScaler()
df[columns_to_standardize] = scaler.fit_transform(df[columns_to_standardize])


In [6]:
df.head(5)

X1        X2        X3        X4        X5        X6        X7  \
0  0.639947  0.848324  0.149641  0.907270 -0.692891  0.204013  0.468492   
1 -0.844885 -1.123396 -0.160546  0.530902 -0.692891 -0.684422 -0.365061   
2  1.233880  1.943724 -0.263941 -1.288212 -0.692891 -1.103255  0.604397   
3 -0.844885 -0.998208 -0.160546  0.154533  0.123302 -0.494043 -0.920763   
4 -1.141852  0.504055 -1.504687  0.907270  0.765836  1.409746  5.484909   

         X8  y  
0  1.425995  1  
1 -0.190672  0  
2 -0.105584  1  
3 -1.041549  0  
4 -0.020496  1

In [7]:
X=df.drop('y',axis=1)
y=df['y']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2)

In [8]:
# Nombre d'enregistrements pour l'ensemble d'apprentissage
num_train_records = X_train.shape[0]
print("Nombre d'enregistrements pour l'ensemble d'apprentissage:", num_train_records)

# Nombre d'enregistrements pour l'ensemble de test
num_test_records = X_test.shape[0]
print("Nombre d'enregistrements pour l'ensemble de test:", num_test_records)

Nombre d'enregistrements pour l'ensemble d'apprentissage: 614
Nombre d'enregistrements pour l'ensemble de test: 154


In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Instanciation du modèle de régression logistique
model = LogisticRegression()

# Entraînement du modèle sur les données d'apprentissage
model.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluation des performances du modèle
accuracy = accuracy_score(y_test, y_pred)
print("Précision du modèle :", accuracy)

# Affichage du rapport de classification
print("\nRapport de classification:")
print(classification_report(y_test, y_pred))

# Affichage de la matrice de confusion
print("\nMatrice de confusion:")
print(confusion_matrix(y_test, y_pred))

Précision du modèle : 0.7857142857142857

Rapport de classification:
              precision    recall  f1-score   support

           0       0.80      0.89      0.84        97
           1       0.76      0.61      0.68        57

    accuracy                           0.79       154
   macro avg       0.78      0.75      0.76       154
weighted avg       0.78      0.79      0.78       154


Matrice de confusion:
[[86 11]
 [22 35]]


In [10]:
# Affichage des paramètres du modèle
print("Coefficients du modèle (poids) :", model.coef_)
print("biais du modèle :", model.intercept_)

Coefficients du modèle (poids) : [[ 0.3390387   1.0977692  -0.28295734 -0.03499758 -0.15482762  0.73750263
   0.2831537   0.1947128 ]]
biais du modèle : [-0.85754688]


In [11]:
# Prédiction sur l'ensemble de test
y_pred = model.predict(X_test)

# Affichage des prédictions
print("Prédictions sur l'ensemble de test :")
print(y_pred)

Prédictions sur l'ensemble de test :
[0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0
 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0
 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0
 1 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0]


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print("Matrice de confusion:")
print(confusion_matrix(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", accuracy)

precision = precision_score(y_test, y_pred)
print("Precision :", precision)

recall = recall_score(y_test, y_pred)
print("Recall :", recall)

f1 = f1_score(y_test, y_pred)
print("F1-score :", f1)

Matrice de confusion:
[[86 11]
 [22 35]]
Accuracy : 0.7857142857142857
Precision : 0.7608695652173914
Recall : 0.6140350877192983
F1-score : 0.679611650485437


In [13]:
from neural import Perceptron

# Évaluation du modèle
model = Perceptron()
model.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluation des performances du modèle
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Matrice de confusion
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matrice de confusion:")
print(conf_matrix)

# Exactitude (accuracy)
accuracy = accuracy_score(y_test, y_pred)
print("Exactitude (Accuracy) :", accuracy)

# Précision (precision)
precision = precision_score(y_test, y_pred)
print("Précision (Precision) :", precision)

# Rappel (recall)
recall = recall_score(y_test, y_pred)
print("Rappel (Recall) :", recall)

# Score F1 (f1-score)
f1 = f1_score(y_test, y_pred)
print("Score F1 (F1-score) :", f1)

100 :  [0.07993639 0.19112463 0.00722477 0.02074427 0.03880282 0.12187527
 0.06321427 0.09051545] -0.13922512309487817
1000 :  [ 0.25462642  0.79129983 -0.14591942 -0.01790899 -0.01835404  0.50518507
  0.22453237  0.22647412] -0.6492517661923293
Matrice de confusion:
[[85 12]
 [22 35]]
Exactitude (Accuracy) : 0.7792207792207793
Précision (Precision) : 0.7446808510638298
Rappel (Recall) : 0.6140350877192983
Score F1 (F1-score) : 0.673076923076923


In [14]:
print(y_pred)

[0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0
 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0
 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0
 1 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0]
